# 🏏 CricketIQ 2.0 — Notebook 01: Environment Setup & Data Ingestion
## BCA Machine Learning Project Pipeline — Phase 1

**Objective:**
1. Configure reproducible Python environment and visualization themes.
2. Ingest official IPL historical matches (2008–2024) and ball-by-ball delivery records (260,000+ rows).
3. Ingest verified 2025/2026 post-mega auction team rosters.

In [1]:
import sys
import os
import warnings
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')
np.random.seed(42)

# Visualization settings
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['font.size'] = 11

# Resolve workspace directory
BASE_DIR = Path("..").resolve() if Path("..").resolve().name == "CricketIQ 2.0" else Path(".").resolve()
sys.path.insert(0, str(BASE_DIR))

print(f"✅ Environment initialized.")
print(f"📁 Workspace: {BASE_DIR}")
print(f"🐍 Python: {sys.version.split()[0]}")

✅ Environment initialized.
📁 Workspace: C:\Users\JAYDEEP MODI\OneDrive\Desktop\CricketIQ 2.0
🐍 Python: 3.13.5

### Ingest Historical Matches and Ball-by-Ball Records

In [2]:
from src.data_loader import load_data, CURRENT_TEAMS
from src.squad_data import get_squad_data

matches, deliveries = load_data(BASE_DIR)
squads_2026 = get_squad_data(BASE_DIR)

print(f"📊 Historical Matches Loaded: {len(matches):,}")
print(f"🏏 Ball-by-Ball Deliveries Loaded: {len(deliveries):,}")
print(f"📅 Seasons: {matches['season'].min()} to {matches['season'].max()}")
print(f"🏟️ Unique Venues: {matches['venue'].nunique()}")
print(f"👥 Active IPL Franchises (2026): {len(CURRENT_TEAMS)}")

display(matches[['id', 'season', 'date', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner']].head(5))

📊 Historical Matches Loaded: 1,090
🏏 Ball-by-Ball Deliveries Loaded: 260,920
📅 Seasons: 2007/08 to 2024
🏟️ Unique Venues: 38
👥 Active IPL Franchises (2026): 10

       id   season  ... toss_decision                       winner
0  335982  2007/08  ...         field        Kolkata Knight Riders
1  335983  2007/08  ...           bat          Chennai Super Kings
2  335984  2007/08  ...           bat               Delhi Capitals
3  335985  2007/08  ...           bat  Royal Challengers Bengaluru
4  335986  2007/08  ...           bat        Kolkata Knight Riders

[5 rows x 8 columns]

### Inspect Deliveries Dataset Structure

In [3]:
display(deliveries[['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball', 'batter', 'bowler', 'batsman_runs', 'extra_runs', 'is_wicket']].head(5))

   match_id  inning  ...  extra_runs  is_wicket
0    335982       1  ...           1          0
1    335982       1  ...           0          0
2    335982       1  ...           1          0
3    335982       1  ...           0          0
4    335982       1  ...           0          0

[5 rows x 11 columns]